export const cart = {
    ADD_TO_CART: 'ADD_TO_CART',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    DECREASE_PRODUCT: 'DECREASE_PRODUCT',
    SET_ACTIVE_PRODUCT: 'SET_ACTIVE_PRODUCT',
    SET_CART_EMPTY: 'SET_CART_EMPTY',
};